Wowoo go 1.1 gets a nil crash that's quite unreasonable
https://travis-ci.org/polydawn/meep/jobs/141422529

Leading text:

"""
--- FAIL: TestAutodescribePlusTraceableCauseDoubleTrouble-2 (0.00 seconds)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x23 pc=0x43420d]
goroutine 8 [running]:
testing.func·004()
	/usr/local/go/src/pkg/testing/testing.go:348 +0xcd
_/home/travis/gopath/src/github.com/polydawn/meep.func·002(0x501c20, 0xc20006fc50, 0x196, 0xc20004d3f0, 0xc2000a2720, ...)
	/home/travis/gopath/src/github.com/polydawn/meep/autodescriber.go:35 +0x20d
_/home/travis/gopath/src/github.com/polydawn/meep.func·004()
	/home/travis/gopath/src/github.com/polydawn/meep/autodescriber.go:85 +0x73
_/home/travis/gopath/src/github.com/polydawn/meep.(*AutodescribingError).ErrorMessage(0xc20006fc58, 0x7fc0cddafb98, 0x10009c750)
	/home/travis/gopath/src/github.com/polydawn/meep/autodescriber.go:105 +0x539
"""

That line citied there is `msg := []byte(m.Cause.Error())`.  There's a check against `m.Cause` being nil an inch above.  This looks suuuper silly to me.

Signed-off-by: Eric Myhre <hash@exultant.us>